import type { ProviderPreset, ProviderPresetId } from "@ai-novel-diagnosis/ai-core";

export const providerPresets: Record<ProviderPresetId, ProviderPreset> = {
	custom: {
		label: "自定义模型服务",
		kind: "openai-compatible",
		baseUrl: "",
		model: "",
		modelOptions: [],
		jsonMode: false,
		needsApiKey: true,
	},
	"shared-gpu": {
		label: "免费共享算力",
		kind: "openai-compatible",
		baseUrl: "",
		model: "",
		modelOptions: [],
		jsonMode: false,
		needsApiKey: false,
		notice: "默认可直接使用。若服务端未配置专用共享线路，系统会自动回退到匿名公共共享池；可能排队、变慢、失败、可分析字数变少或输出质量波动，不建议上传未授权原文、隐私内容或商业机密。",
	},
	deepseek: {
		label: "DeepSeek",
		kind: "openai-compatible",
		baseUrl: "https://api.deepseek.com/v1",
		model: "deepseek-chat",
		modelOptions: ["deepseek-chat", "deepseek-reasoner"],
		jsonMode: false,
		needsApiKey: true,
	},
	doubao: {
		label: "豆包/火山方舟",
		kind: "openai-compatible",
		baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
		model: "doubao-seed-1-6",
		modelOptions: ["doubao-seed-1-6"],
		jsonMode: false,
		needsApiKey: true,
	},
	qwen: {
		label: "阿里云百炼/通义千问",
		kind: "openai-compatible",
		baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
		model: "qwen-plus",
		modelOptions: [
			"qwen-plus",
			"qwen-plus-latest",
			"qwen3-max",
			"qwen3-max-preview",
			"qwen-max",
			"qwen-max-latest",
			"qwen-flash",
			"qwen-turbo",
			"qwen-turbo-latest",
			"qwen3.5-plus",
			"qwen3.5-flash",
			"qwen3-coder-plus",
			"qwen3-coder-flash",
			"qwq-plus",
		],
		jsonMode: false,
		needsApiKey: true,
	},
	ollama: {
		label: "Ollama 本地模型",
		kind: "openai-compatible",
		baseUrl: "http://localhost:11434/v1",
		model: "qwen2.5:7b",
		modelOptions: ["qwen2.5:7b", "qwen3:8b", "llama3.1:8b"],
		jsonMode: false,
		needsApiKey: false,
	},
};
